# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 36f535ac87a6cce137e332838af914d3f45e9dd294bbd5304b0b030e59dd08c28169a3d6b68ffaf40c78a2062c72e924c4f7728957ff22a8e675772c76d6e77e

test:
  secret_key_base: 8f56899ed416e2d41e8dda02a5cc3bf8570991b4590b8625864cb3972b416674075fd9f4e295e07f01e233a4b9c49f1196984ef586145b79ed33525b8a2079d1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
